const Styles={
    container:{
        width:'100%',
        backgroundColor:'white',
        elevation:5,
        marginTop:20
    },
    year:{
        width:'100%',
        fontSize:20,
        padding:10,

    },
    header:{
        width:'100%',
        backgroundColor:'white',
        borderBottomWidth:1,
        borderColor:'grey'
    },
    day:{
        fontSize:20,
        width:'100%',
        textAlign:'center',
        paddingTop:10
    },
    date:{
        fontSize:30,
        width:'100%',
        textAlign:'center',
        padding:10,
        paddingTop:0,
        color:'black',
        fontWeight:'bold'
    },
    time:{
        fontSize:15,
        fontWeight:'bold',
        color:'black',
        padding:10
    },
    heading:{
        fontSize:30,
        width:400,
        color:'black',
        fontWeight:'bold',
        padding:10
    },
    text:{
        padding:20,
        paddingBottom:0,
        fontSize:15,
        color:'black'
    },
    showmore:{
        fontSize:15,
        fontWeight:'500',
        textDecorationLine: 'underline',
        color:'#6CB4EE',
        padding:10,
        paddingLeft:30
    },
    image:{
        height:200,
        margin:20
    }
}
export default Styles;