const Styles={
    container:{
        height:'100%',
        width:'100%',
        alignItems:'center',
        backgroundColor:'white',
    },
    container2:{
        width:'100%',
        flexDirection:'row',
        justifyContent:'space-between',
        height:100,
        padding:5
    },
    firstinput:{
        width:'46%',
        height:30,
    },
    lastinput:{
        width:'46%',
        height:30,
    },
    emailcontainer:{
      width:'100%',
      margin:10,
      height:100,
  },
    email:{
        width:'100%',
        height:30,
    },
    messagecontainer:{
      width:'100%',
      margin:10,
      height:250,
  },
    message:{
        width:'100%',
        height:150,
    },
    btncontainer:{
        height:65, 
        width:'100%',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#002D62',
        borderRadius:15,
        elevation:5,
        marginTop:60,
    },
    btntext:{
        fontSize:20,
        fontWeight:'bold',
        color:'white'
    }
}
export default Styles;