const Styles = {
    container:{
        height:'100%',
        width:'100%',
        alignItems:'center'
    },
    heading:{
        fontSize:30,
        width:400,
        color:'black',
        fontWeight:'bold',
        padding:10
    },
    image:{
        height:400,
        width:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    date:{
        width:400,
        fontSize:17,
        color:'black',
        fontWeight:'bold',
        marginTop:20,
        paddingLeft:10
    },
    btncontainer:{
        width:400,
        alignItems:'flex-end',
        padding:10
    },
    btntxt:{
        textAlign:'center',
        width:170,
        height:30,
        paddingTop:2,
        borderRadius:50,
        elevation:5,
        color:'white',
        fontSize:17,
        backgroundColor:'#002D62',
        fontWeight:'400'
    },
    container2:{
        width:'100%',
        height:280,
        margin:10,
        backgroundColor:'white',
        elevation:5,
        borderRadius:15
    },
    calendar:{
        flexDirection:'row',
        alignItems:'center',
        padding:10
    },
    calendarimg:{
        height:30,
        width:30,
    },
    calendarheading:{
        fontSize:20,
        fontWeight:'bold',
        color:'#002D62'
    },
    calendarcontainer:{
        borderBottomWidth:1,
        borderColor:'grey',
        padding:10,
        flexDirection:'column',
        margin:10
    },
    duration:{
        fontSize:15,
        fontWeight:'500',
        color:'#002D62',
        padding:5
    },
    add:{
        fontSize:15,
        color:'#6CB4EE',
        textDecorationLine:'underline' ,
        fontWeight:'bold',
        width:350
    },
    calendarcontainer2:{
        padding:10,
        flexDirection:'column',
        margin:10
    },
    descheading:{
        fontSize:30,
        fontWeight:'bold',
        color:'black',
        width:400,
        padding:15
    },
    desc:{
        width:380,
        fontSize:17,
        color:'black',
        padding:15,
        fontWeight:'400'
    },
    mapcontainer:{
        borderWidth:2,
        height:500,
        width:'100%',
        padding:10,
        margin:10,
        borderRadius:15,
        borderColor:'blue',
        flex:1
    },
    map:{
        flex:1,
    }
}
export default Styles;